GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjI4NDkxNjA5LCJleHAiOjE2Mjg0OTE2MjR9.U6psiexX-gqS5Ms_Y_DJkLXmVheEbRUXmP7J21Q07r4

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjI4NDkxNjU5LCJleHAiOjE2Mjg0OTE2NzR9.POozR0FO9EEotkkRqSJ1CvdM8jkkZEx9mnXTZQXXPa4"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}